# step - 1 when should this pipeline run

name: Deploy to Staging

on:
  push:
    branches:
      - "main"

# jab bhi main branch pr kuch push ho tab run these jobs

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Redeploy Everything to staging cluster

    # ab jo ye redeploy everything job hai use kya kya krna hoga

    steps:
      - name: SSH into SERVER

        # &> means pipe it into ssh_key file

        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key

          chmod 400 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.127.191.19 << 'EOF'

            cd deployment-CI-CD/ && git pull

            npm install

            npm run build

            pm2 restart all

          EOF